<#
.SYNOPSIS
Run on WS01 (the victim). Stages the phase-1 delivery files into the
lab staging directory C:\Users\Public\C0015\:
  - config.ini (generated by make_config.ps1)
  - bootstrap.hta
  - c0015_beacon.ps1
The DLL itself is NOT staged here: the HTA downloads it from the attacker
HTTP server at runtime (T1105 / T1036), mirroring the campaign delivery.

.PARAMETER Source  Folder (on WS01) containing config.ini, bootstrap.hta, c0015_beacon.ps1.
.PARAMETER PublicDir  Lab staging directory (default C:\Users\Public\C0015).
.EXAMPLE
pwsh -ExecutionPolicy Bypass -File payloads/packaging/stage_ws01.ps1 -Source C:\stage
#>
param(
    [Parameter(Mandatory=$true)][string]$Source,
    [string]$PublicDir = 'C:\Users\Public\C0015'
)
$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path $PublicDir | Out-Null
foreach ($f in @('config.ini','bootstrap.hta','c0015_beacon.ps1')) {
    $src = Join-Path $Source $f
    if (-not (Test-Path -LiteralPath $src)) { throw "missing staging file: $src" }
    Copy-Item -LiteralPath $src -Destination $PublicDir -Force
}
Write-Output "staged into $PublicDir :"
Get-ChildItem -LiteralPath $PublicDir -File | Select-Object Name,Length | Format-Table -AutoSize
Write-Output "The DLL is downloaded by the HTA from the attacker HTTP server at runtime (not staged)."